const names = [
    "Abigail Adams",
    "Alexander Hamilton",
    "Alicia Keys",
    "Amelia Earhart",
    "Andrew Jackson",
    "Angelina Jolie",
    "Anna Kendrick",
    "Anne Hathaway",
    "Arnold Schwarzenegger",
    "Audrey Hepburn",
    "Barack Obama",
    "Beyoncé Knowles",
    "Bill Clinton",
    "Blake Lively",
    "Brad Pitt",
    "Britney Spears",
    "Bruce Lee",
    "Cameron Diaz",
    "Catherine Zeta-Jones",
    "Charles Darwin",
    "Charlize Theron",
    "Chris Evans",
    "Chris Hemsworth",
    "Christian Bale",
    "Christopher Columbus",
    "Clint Eastwood",
    "Dakota Johnson",
    "Daniel Craig",
    "Daniel Radcliffe",
    "David Beckham",
    "David Bowie",
    "David Letterman",
    "Demi Lovato",
    "Diana Ross",
    "Drew Barrymore",
    "Dwayne Johnson",
    "Ed Sheeran",
    "Elon Musk",
    "Emma Roberts",
    "Emma Stone",
    "Emma Watson",
    "Eva Longoria",
    "George Clooney",
    "George Washington",
    "Gigi Hadid",
    "Gisele Bündchen",
    "Halle Berry",
    "Harrison Ford",
    "Heath Ledger",
    "Hilary Duff",
    "Hugh Jackman",
    "Ian Somerhalder",
    "Idris Elba",
    "Isaac Newton",
    "Jackie Chan",
    "James Franco",
    "Jamie Foxx",
    "Jason Statham",
    "Jennifer Aniston",
    "Jennifer Lawrence",
    "Jennifer Lopez",
    "Jessica Alba",
    "Jessica Biel",
    "Jim Carrey",
    "Joan Rivers",
    "John F. Kennedy",
    "John Legend",
    "Johnny Depp",
    "Julia Roberts",
    "Justin Bieber",
    "Kanye West",
    "Katherine Hepburn",
    "Keanu Reeves",
    "Keira Knightley",
    "Kendall Jenner",
    "Kerry Washington",
    "Kevin Hart",
    "Kim Kardashian",
    "Kristen Bell",
    "Kristen Stewart",
    "Lady Gaga",
    "Lana Del Rey",
    "Leonardo DiCaprio",
    "Liam Hemsworth",
    "Lindsay Lohan",
    "Lucille Ball",
    "Madonna",
    "Marilyn Monroe",
    "Mark Wahlberg",
    "Meryl Streep",
    "Michael Jackson",
    "Michelle Obama",
    "Mila Kunis",
    "Miley Cyrus",
    "Morgan Freeman",
    "Natalie Portman",
    "Neil Armstrong",
    "Nicole Kidman",
    "Oprah Winfrey",
    "Orlando Bloom",
    "Patrick Stewart",
    "Paul McCartney",
    "Penélope Cruz",
    "Prince William",
    "Queen Elizabeth II",
    "Rihanna",
    "Robert De Niro",
    "Robert Downey Jr.",
    "Ryan Gosling",
    "Ryan Reynolds",
    "Salma Hayek",
    "Samuel L. Jackson",
    "Scarlett Johansson",
    "Sean Connery",
    "Selena Gomez",
    "Serena Williams",
    "Shakira",
    "Shia LaBeouf",
    "Steve Jobs",
    "Steven Spielberg",
];  

module.exports = names;